// ─── Puzzle Data ───
const PUZZLES = [
  {
    id: 1, category: 'منطق الأرقام', catIcon: '🔢', title: 'ما العدد الناقص؟',
    description: 'أكمل المتتالية التالية',
    difficulty: 'متوسط', timeEstimate: '٢ دقيقة', isPremium: false,
    type: 'text',
    question: '٢ ، ٥ ، ١٠ ، ١٧ ، ؟',
    answer: '26',
    acceptedAnswers: ['26', '٢٦'],
    hints: ['الفرق بين كل عددين يزيد بمقدار ٢', 'الفروق: ٣، ٥، ٧، ...', 'الفرق التالي هو ٩'],
    cognitiveBenefit: 'تحسين التفكير التسلسلي والتعرف على الأنماط الرياضية',
    points: 15,
  },
  {
    id: 2, category: 'منطق الأرقام', catIcon: '🔢', title: 'المعادلة المخفية',
    description: 'اكتشف الرقم المجهول',
    difficulty: 'صعب', timeEstimate: '٣ دقائق', isPremium: false,
    type: 'text',
    question: 'إذا كان: ٣ ⊕ ٤ = ٢٥ و ٥ ⊕ ٢ = ٢٩ و ٧ ⊕ ١ = ٥٠ فما هو ٦ ⊕ ٣ = ؟',
    answer: '45',
    acceptedAnswers: ['45', '٤٥'],
    hints: ['العملية ليست جمع أو ضرب بسيط', 'جرب تربيع الأعداد ثم جمعها', 'a² + b² = النتيجة: ٣²+٤²=٩+١٦=٢٥'],
    cognitiveBenefit: 'تعزيز التفكير المنطقي واكتشاف العلاقات المخفية',
    points: 25,
  },
  {
    id: 3, category: 'لغز الكلمات', catIcon: '🔤', title: 'كلمة من ٥ أحرف',
    description: 'اكتشف الكلمة من التعريف',
    difficulty: 'متوسط', timeEstimate: '٢ دقيقة', isPremium: false,
    type: 'text',
    question: 'كلمة من ٥ أحرف تعني "الشخص الذي يفكر بعمق ويتأمل"',
    answer: 'مفكر',
    acceptedAnswers: ['مفكر'],
    hints: ['تبدأ بحرف الميم', 'لها علاقة بالفكر والتأمل', 'م ف ك ر'],
    cognitiveBenefit: 'تنشيط الذاكرة اللغوية والربط الدلالي',
    points: 15,
  },
  {
    id: 4, category: 'لغز الكلمات', catIcon: '🔤', title: 'أعد ترتيب الحروف',
    description: 'رتب الحروف لتكوين كلمة ذات معنى',
    difficulty: 'صعب', timeEstimate: '٣ دقائق', isPremium: false,
    type: 'text',
    question: 'رتب هذه الحروف: ر - ا - ب - ت - خ',
    answer: 'اختبار',
    acceptedAnswers: ['اختبار'],
    hints: ['الكلمة مكونة من ٥ أحرف + حرف إضافي', 'لها علاقة بالامتحانات', 'تبدأ بألف'],
    cognitiveBenefit: 'تحسين المرونة العقلية وإعادة الهيكلة الذهنية',
    points: 25,
  },
  {
    id: 5, category: 'الذاكرة العاملة', catIcon: '🧠', title: 'تذكّر التسلسل',
    description: 'احفظ سلسلة الأرقام ثم أعد كتابتها',
    difficulty: 'متوسط', timeEstimate: '١ دقيقة', isPremium: false,
    type: 'memory',
    sequences: [
      { numbers: [3, 7, 1, 9], display: '٣ ٧ ١ ٩' },
      { numbers: [5, 2, 8, 4, 6], display: '٥ ٢ ٨ ٤ ٦' },
      { numbers: [9, 1, 4, 7, 2, 8], display: '٩ ١ ٤ ٧ ٢ ٨' },
    ],
    hints: ['حاول تجميع الأرقام في مجموعات', 'كرر الأرقام في ذهنك', 'اربط كل رقم بصورة ذهنية'],
    cognitiveBenefit: 'تقوية الذاكرة العاملة والاحتفاظ بالمعلومات المؤقتة',
    points: 20,
  },
  {
    id: 6, category: 'الذاكرة العاملة', catIcon: '🧠', title: 'تحدي N-Back',
    description: 'هل هذا الرقم ظهر قبل خطوتين؟',
    difficulty: 'صعب', timeEstimate: '٣ دقائق', isPremium: false,
    type: 'nback',
    sequence: [3, 5, 3, 7, 5, 2, 7, 4, 2, 8],
    hints: ['ركز على الرقم الذي ظهر قبل خطوتين فقط', 'لا تحاول حفظ كل الأرقام', 'استخدم تقنية التكرار الذهني'],
    cognitiveBenefit: 'تحسين الذاكرة العاملة - مثبت علمياً أنه يرفع الذكاء السائل',
    points: 30,
  },
  {
    id: 7, category: 'التفكير البصري', catIcon: '👁️', title: 'أي شكل لا ينتمي؟',
    description: 'اختر الشكل المختلف من المجموعة',
    difficulty: 'متوسط', timeEstimate: '١ دقيقة', isPremium: false,
    type: 'choices',
    question: 'أي من هذه الأشكال لا ينتمي للمجموعة؟',
    choices: ['🔵 دائرة زرقاء', '🟢 دائرة خضراء', '🔴 دائرة حمراء', '🟥 مربع أحمر'],
    correctIndex: 3,
    hints: ['انظر إلى الشكل وليس اللون فقط', 'ثلاثة أشكال متشابهة في النوع', 'المربع مختلف عن الدوائر'],
    cognitiveBenefit: 'تطوير التفكير التحليلي والتصنيف البصري',
    points: 15,
  },
  {
    id: 8, category: 'التفكير البصري', catIcon: '👁️', title: 'أكمل النمط',
    description: 'اكتشف النمط واختر الشكل التالي',
    difficulty: 'صعب', timeEstimate: '٣ دقائق', isPremium: false,
    type: 'choices',
    question: 'ما الشكل التالي في النمط: ⬛ ⬜ ⬛ ⬜ ⬛ ⬜ ؟',
    choices: ['⬛ أسود', '⬜ أبيض', '🟦 أزرق', '🟨 أصفر'],
    correctIndex: 0,
    hints: ['النمط يتناوب بين لونين', 'أسود ثم أبيض ثم أسود...', 'الشكل التالي بعد الأبيض هو...'],
    cognitiveBenefit: 'تعزيز التعرف على الأنماط المتكررة والتنبؤ',
    points: 25,
  },
  {
    id: 9, category: 'السرعة والتركيز', catIcon: '⚡', title: 'تحدي الـ ٦٠ ثانية',
    description: 'حل أكبر عدد من العمليات الحسابية في ٦٠ ثانية',
    difficulty: 'صعب', timeEstimate: '١ دقيقة', isPremium: false,
    type: 'blitz',
    hints: ['ركز على السرعة لا الدقة المطلقة', 'ابدأ من اليسار لليمين', 'تجاوز الأسئلة الصعبة'],
    cognitiveBenefit: 'تحسين سرعة المعالجة الذهنية والحساب الذهني',
    points: 30,
  },
  {
    id: 10, category: 'السرعة والتركيز', catIcon: '⚡', title: 'اختبار ستروب',
    description: 'اختر لون الكتابة وليس الكلمة المكتوبة',
    difficulty: 'صعب', timeEstimate: '٢ دقيقة', isPremium: false,
    type: 'stroop',
    rounds: 10,
    hints: ['تجاهل ما تقرأه وركز على اللون', 'لا تقرأ الكلمة أبداً', 'انظر إلى اللون فقط'],
    cognitiveBenefit: 'تقوية التحكم التنفيذي ومقاومة التشتت — أساس التركيز',
    points: 30,
  },
  {
    id: 11, category: 'منطق الأرقام', catIcon: '🔢', title: 'المربع السحري',
    description: 'أكمل المربع بحيث يكون مجموع كل صف وعمود متساوياً',
    difficulty: 'صعب', timeEstimate: '٥ دقائق', isPremium: true,
    type: 'text',
    question: 'في مربع ٣×٣ يحتوي على الأرقام ١ إلى ٩، مجموع كل صف وعمود وقطر = ١٥. ما الرقم في المركز؟',
    answer: '5',
    acceptedAnswers: ['5', '٥'],
    hints: ['المجموع الكلي لـ ١-٩ هو ٤٥', '٤٥ ÷ ٣ = ١٥ لكل صف', 'الرقم المركزي هو المتوسط'],
    cognitiveBenefit: 'تحسين التفكير المكاني والحساب المنطقي المتقدم',
    points: 35,
  },
  {
    id: 12, category: 'لغز الكلمات', catIcon: '🔤', title: 'الكلمة المشتركة',
    description: 'جد الكلمة التي تربط بين ثلاث كلمات',
    difficulty: 'متوسط', timeEstimate: '٢ دقيقة', isPremium: true,
    type: 'text',
    question: 'ما الكلمة المشتركة بين: شمس ، قمر ، نجم ؟',
    answer: 'سماء',
    acceptedAnswers: ['سماء', 'السماء', 'فضاء', 'الفضاء'],
    hints: ['كلها أجرام تظهر في مكان واحد', 'ارفع رأسك للأعلى', 'المكان الذي نرى فيه هذه الأشياء'],
    cognitiveBenefit: 'تنشيط الشبكات الدلالية وتحسين الربط المفاهيمي',
    points: 15,
  },
];

const CATEGORIES = [
  { id: 'numbers', name: 'منطق الأرقام', icon: '🔢', description: 'تحديات رياضية ومتتاليات تشحذ التفكير المنطقي', color: '#4F46E5' },
  { id: 'words', name: 'لغز الكلمات', icon: '🔤', description: 'ألغاز لغوية تنشط الذاكرة اللفظية والربط الدلالي', color: '#059669' },
  { id: 'memory', name: 'الذاكرة العاملة', icon: '🧠', description: 'تمارين مثبتة علمياً لتقوية الذاكرة قصيرة المدى', color: '#7C3AED' },
  { id: 'visual', name: 'التفكير البصري', icon: '👁️', description: 'أنماط وأشكال تطور التحليل البصري المكاني', color: '#DC2626' },
  { id: 'speed', name: 'السرعة والتركيز', icon: '⚡', description: 'تحديات زمنية تحسن سرعة المعالجة الذهنية', color: '#D97706' },
];

function getPuzzlesByCategory(categoryName) {
  return PUZZLES.filter(p => p.category === categoryName);
}
